IP_ADDR = "192.168.55.10"
HOST_DIR = "./"
VM_DIR =  "/home/vagrant/shared"

Vagrant.configure("2") do |config|

  config.vm.box = "meech-ward/lamp"

  config.vm.network :private_network, ip: IP_ADDR

  config.vm.synced_folder HOST_DIR, VM_DIR

  config.trigger.after :up, :reload do |trigger|
    trigger.info = "Restarting Apache"
    trigger.run_remote = {inline: "docker restart apache-server"}
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ 'modifyvm', :id, '--uartmode1', 'disconnected']
  end

end
